### ISSUE TITLE
early stopping doesn't work

### ISSUE THREAD

**Issue by MaximilianPi** [citoverse/cito#29]
```
  library(cito)
  
  set.seed(222)
  validation_set<- sample(c(1:nrow(datasets::iris)),25)
  
  # Build and train  Network
  nn.fit<- dnn(Sepal.Length~., 
               data = datasets::iris[-validation_set,], epochs = 400, early_stopping = 5)
```

**Comment by MaximilianPi** [comment]
Ausserdem scheint es so implemtentiert zu sein dass es nur funktioniert wenn es einen validation split gibt? Waere nice wenn das early stopping auf dem trainings loss basiert wenn es kein validation set gibt

**Comment by ChristianAmes** [comment]
Finde ich einen schönen wg, Danke!
