### ISSUE TITLE
Gewichte pro Epoche speichern

### ISSUE THREAD

**Issue by MaximilianPi** [citoverse/cito#45]
Bei grossen NN laeuft der Arbeitspeicher voll wenn die Gewichte jede Epoche gespeichert werden:

<img width="562" alt="image" src="https://github.com/citoverse/cito/assets/29951520/74b2e28a-5653-4bdb-88fa-fac2a16ff48d">

Sollten nur die letzte Epoche und evtl. die beste Epoche (vom val. loss) speichern

**Comment by ChristianAmes** [comment]
Sehe ich als sinnvoll an, sollen wir das als Standard machen oder als Option mit einbauen ?

**Comment by MaximilianPi** [comment]
Gute Idee, default + option fuer jede Epoche
